[package]
name = "factorio-map-art"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0.23"
clap = { version = "3.1.17", features = ["derive"] }
base64 = "0.13.0"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
image = "0.24.2"
pbr = "1.0.4"
